### ISSUE TITLE
Updates on a existing fe user not sent to CleverReach

### ISSUE THREAD

**Issue by swisschocolate-zz** [t3premium/femanager_cleverreach#6]
If I edit an existing fe_user, the changes are not transmitted to CleverReach. Creation of a new fe_user however is working.

**Comment by t3premium** [comment]
Hi swisschocolate,
the cleverreach interface is only activated if a new frontend user will register with femanger registration form. Transmitting changes by editing an existing fe_user in the backend will not be part of this extension.

Best regards
Sam

**Comment by swisschocolate-zz** [comment]
Thanks Sam. Sorry for my imprecision: I meant the change in the frontend, if a user changes his account in the frontend via femanager edit form. Could this be done/sponsored?

**Comment by t3premium** [comment]
Do you want to make a feature branch? I'll merge it to the next release.
