### ISSUE TITLE
Add more fields

### ISSUE THREAD

**Issue by ipnextOne** [t3premium/femanager_cleverreach#7]
Hello,

thanks for the great tool.
Is it possible to transfer more fields? I will transferthe usergroup field and add usergroup in CleaverReach, but the data will not transfer. 

Thanks a lot for Help 
Mathias

**Comment by t3premium** [comment]
Hello Matthias,
currently only the fields "Email", "Firstname", "Lastname" are supported.
Maybe in an upcoming release there will be the possibility to add custom fields.
You want to contribute this feature?

Best regards
Sam
